
package mx.buzoncfdi.cfdi33_pruebas;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TimbradoSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TimbradoSoap {


    /**
     * Servicio de registro para emisores
     * 
     * @param usuarioIntegrador
     * @param contrasena
     * @param base64Key
     * @param base64Cer
     * @param rfcEmisor
     * @return
     *     returns mx.buzoncfdi.cfdi33_pruebas.ArrayOfAnyType
     */
    @WebMethod(operationName = "RegistraEmisor", action = "http://tempuri.org/RegistraEmisor")
    @WebResult(name = "RegistraEmisorResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RegistraEmisor", targetNamespace = "http://tempuri.org/", className = "mx.buzoncfdi.cfdi33_pruebas.RegistraEmisor")
    @ResponseWrapper(localName = "RegistraEmisorResponse", targetNamespace = "http://tempuri.org/", className = "mx.buzoncfdi.cfdi33_pruebas.RegistraEmisorResponse")
    public ArrayOfAnyType registraEmisor(
        @WebParam(name = "usuarioIntegrador", targetNamespace = "http://tempuri.org/")
        String usuarioIntegrador,
        @WebParam(name = "rfcEmisor", targetNamespace = "http://tempuri.org/")
        String rfcEmisor,
        @WebParam(name = "base64Cer", targetNamespace = "http://tempuri.org/")
        String base64Cer,
        @WebParam(name = "base64Key", targetNamespace = "http://tempuri.org/")
        String base64Key,
        @WebParam(name = "contrasena", targetNamespace = "http://tempuri.org/")
        String contrasena);

    /**
     * Servicio de timbrado de retenciones y pagos
     * 
     * @param usuarioIntegrador
     * @param xmlComprobanteBase64
     * @param idComprobante
     * @return
     *     returns mx.buzoncfdi.cfdi33_pruebas.ArrayOfAnyType
     */
    @WebMethod(operationName = "TimbraRetencion", action = "http://tempuri.org/TimbraRetencion")
    @WebResult(name = "TimbraRetencionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "TimbraRetencion", targetNamespace = "http://tempuri.org/", className = "mx.buzoncfdi.cfdi33_pruebas.TimbraRetencion")
    @ResponseWrapper(localName = "TimbraRetencionResponse", targetNamespace = "http://tempuri.org/", className = "mx.buzoncfdi.cfdi33_pruebas.TimbraRetencionResponse")
    public ArrayOfAnyType timbraRetencion(
        @WebParam(name = "usuarioIntegrador", targetNamespace = "http://tempuri.org/")
        String usuarioIntegrador,
        @WebParam(name = "xmlComprobanteBase64", targetNamespace = "http://tempuri.org/")
        String xmlComprobanteBase64,
        @WebParam(name = "idComprobante", targetNamespace = "http://tempuri.org/")
        String idComprobante);

    /**
     * Servicio de asignación de timbres para Integradores
     * 
     * @param usuarioIntegrador
     * @param noTimbres
     * @param rfcEmisor
     * @return
     *     returns mx.buzoncfdi.cfdi33_pruebas.ArrayOfAnyType
     */
    @WebMethod(operationName = "AsignaTimbresEmisor", action = "http://tempuri.org/AsignaTimbresEmisor")
    @WebResult(name = "AsignaTimbresEmisorResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AsignaTimbresEmisor", targetNamespace = "http://tempuri.org/", className = "mx.buzoncfdi.cfdi33_pruebas.AsignaTimbresEmisor")
    @ResponseWrapper(localName = "AsignaTimbresEmisorResponse", targetNamespace = "http://tempuri.org/", className = "mx.buzoncfdi.cfdi33_pruebas.AsignaTimbresEmisorResponse")
    public ArrayOfAnyType asignaTimbresEmisor(
        @WebParam(name = "usuarioIntegrador", targetNamespace = "http://tempuri.org/")
        String usuarioIntegrador,
        @WebParam(name = "rfcEmisor", targetNamespace = "http://tempuri.org/")
        String rfcEmisor,
        @WebParam(name = "noTimbres", targetNamespace = "http://tempuri.org/")
        int noTimbres);

    /**
     * Servicio de consulta de timbres para Integradores
     * 
     * @param usuarioIntegrador
     * @param rfcEmisor
     * @return
     *     returns mx.buzoncfdi.cfdi33_pruebas.ArrayOfAnyType
     */
    @WebMethod(operationName = "ObtieneTimbresDisponibles", action = "http://tempuri.org/ObtieneTimbresDisponibles")
    @WebResult(name = "ObtieneTimbresDisponiblesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ObtieneTimbresDisponibles", targetNamespace = "http://tempuri.org/", className = "mx.buzoncfdi.cfdi33_pruebas.ObtieneTimbresDisponibles")
    @ResponseWrapper(localName = "ObtieneTimbresDisponiblesResponse", targetNamespace = "http://tempuri.org/", className = "mx.buzoncfdi.cfdi33_pruebas.ObtieneTimbresDisponiblesResponse")
    public ArrayOfAnyType obtieneTimbresDisponibles(
        @WebParam(name = "usuarioIntegrador", targetNamespace = "http://tempuri.org/")
        String usuarioIntegrador,
        @WebParam(name = "rfcEmisor", targetNamespace = "http://tempuri.org/")
        String rfcEmisor);

    /**
     * Servicio de timbrado para Integradores
     * 
     * @param usuarioIntegrador
     * @param xmlComprobanteBase64
     * @param idComprobante
     * @return
     *     returns mx.buzoncfdi.cfdi33_pruebas.ArrayOfAnyType
     */
    @WebMethod(operationName = "TimbraCFDI", action = "http://tempuri.org/TimbraCFDI")
    @WebResult(name = "TimbraCFDIResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "TimbraCFDI", targetNamespace = "http://tempuri.org/", className = "mx.buzoncfdi.cfdi33_pruebas.TimbraCFDI")
    @ResponseWrapper(localName = "TimbraCFDIResponse", targetNamespace = "http://tempuri.org/", className = "mx.buzoncfdi.cfdi33_pruebas.TimbraCFDIResponse")
    public ArrayOfAnyType timbraCFDI(
        @WebParam(name = "usuarioIntegrador", targetNamespace = "http://tempuri.org/")
        String usuarioIntegrador,
        @WebParam(name = "xmlComprobanteBase64", targetNamespace = "http://tempuri.org/")
        String xmlComprobanteBase64,
        @WebParam(name = "idComprobante", targetNamespace = "http://tempuri.org/")
        String idComprobante);

    /**
     * Servicio de cancelación CFDI
     * 
     * @param usuarioIntegrador
     * @param folioUUID
     * @param rfcEmisor
     * @return
     *     returns mx.buzoncfdi.cfdi33_pruebas.ArrayOfAnyType
     */
    @WebMethod(operationName = "CancelaCFDI", action = "http://tempuri.org/CancelaCFDI")
    @WebResult(name = "CancelaCFDIResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CancelaCFDI", targetNamespace = "http://tempuri.org/", className = "mx.buzoncfdi.cfdi33_pruebas.CancelaCFDI")
    @ResponseWrapper(localName = "CancelaCFDIResponse", targetNamespace = "http://tempuri.org/", className = "mx.buzoncfdi.cfdi33_pruebas.CancelaCFDIResponse")
    public ArrayOfAnyType cancelaCFDI(
        @WebParam(name = "usuarioIntegrador", targetNamespace = "http://tempuri.org/")
        String usuarioIntegrador,
        @WebParam(name = "rfcEmisor", targetNamespace = "http://tempuri.org/")
        String rfcEmisor,
        @WebParam(name = "folioUUID", targetNamespace = "http://tempuri.org/")
        String folioUUID);

    /**
     * Servicio de cancelación CFDI con acuse
     * 
     * @param usuarioIntegrador
     * @param folioUUID
     * @param rfcEmisor
     * @return
     *     returns mx.buzoncfdi.cfdi33_pruebas.ArrayOfAnyType
     */
    @WebMethod(operationName = "CancelaCFDIAck", action = "http://tempuri.org/CancelaCFDIAck")
    @WebResult(name = "CancelaCFDIAckResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CancelaCFDIAck", targetNamespace = "http://tempuri.org/", className = "mx.buzoncfdi.cfdi33_pruebas.CancelaCFDIAck")
    @ResponseWrapper(localName = "CancelaCFDIAckResponse", targetNamespace = "http://tempuri.org/", className = "mx.buzoncfdi.cfdi33_pruebas.CancelaCFDIAckResponse")
    public ArrayOfAnyType cancelaCFDIAck(
        @WebParam(name = "usuarioIntegrador", targetNamespace = "http://tempuri.org/")
        String usuarioIntegrador,
        @WebParam(name = "rfcEmisor", targetNamespace = "http://tempuri.org/")
        String rfcEmisor,
        @WebParam(name = "folioUUID", targetNamespace = "http://tempuri.org/")
        String folioUUID);

    /**
     * Servicio de cancelación de retenciones y pagos
     * 
     * @param usuarioIntegrador
     * @param folioUUID
     * @param rfcEmisor
     * @return
     *     returns mx.buzoncfdi.cfdi33_pruebas.ArrayOfAnyType
     */
    @WebMethod(operationName = "CancelaRetencion", action = "http://tempuri.org/CancelaRetencion")
    @WebResult(name = "CancelaRetencionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CancelaRetencion", targetNamespace = "http://tempuri.org/", className = "mx.buzoncfdi.cfdi33_pruebas.CancelaRetencion")
    @ResponseWrapper(localName = "CancelaRetencionResponse", targetNamespace = "http://tempuri.org/", className = "mx.buzoncfdi.cfdi33_pruebas.CancelaRetencionResponse")
    public ArrayOfAnyType cancelaRetencion(
        @WebParam(name = "usuarioIntegrador", targetNamespace = "http://tempuri.org/")
        String usuarioIntegrador,
        @WebParam(name = "rfcEmisor", targetNamespace = "http://tempuri.org/")
        String rfcEmisor,
        @WebParam(name = "folioUUID", targetNamespace = "http://tempuri.org/")
        String folioUUID);

    /**
     * Servicio de consulta CFDI
     * 
     * @param usuarioIntegrador
     * @param folioUUID
     * @param rfcEmisor
     * @return
     *     returns mx.buzoncfdi.cfdi33_pruebas.ArrayOfAnyType
     */
    @WebMethod(operationName = "ObtieneCFDI", action = "http://tempuri.org/ObtieneCFDI")
    @WebResult(name = "ObtieneCFDIResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ObtieneCFDI", targetNamespace = "http://tempuri.org/", className = "mx.buzoncfdi.cfdi33_pruebas.ObtieneCFDI")
    @ResponseWrapper(localName = "ObtieneCFDIResponse", targetNamespace = "http://tempuri.org/", className = "mx.buzoncfdi.cfdi33_pruebas.ObtieneCFDIResponse")
    public ArrayOfAnyType obtieneCFDI(
        @WebParam(name = "usuarioIntegrador", targetNamespace = "http://tempuri.org/")
        String usuarioIntegrador,
        @WebParam(name = "rfcEmisor", targetNamespace = "http://tempuri.org/")
        String rfcEmisor,
        @WebParam(name = "folioUUID", targetNamespace = "http://tempuri.org/")
        String folioUUID);

    /**
     * Servicio de consulta retenciones y pagos
     * 
     * @param usuarioIntegrador
     * @param folioUUID
     * @param rfcEmisor
     * @return
     *     returns mx.buzoncfdi.cfdi33_pruebas.ArrayOfAnyType
     */
    @WebMethod(operationName = "ObtieneRetencion", action = "http://tempuri.org/ObtieneRetencion")
    @WebResult(name = "ObtieneRetencionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ObtieneRetencion", targetNamespace = "http://tempuri.org/", className = "mx.buzoncfdi.cfdi33_pruebas.ObtieneRetencion")
    @ResponseWrapper(localName = "ObtieneRetencionResponse", targetNamespace = "http://tempuri.org/", className = "mx.buzoncfdi.cfdi33_pruebas.ObtieneRetencionResponse")
    public ArrayOfAnyType obtieneRetencion(
        @WebParam(name = "usuarioIntegrador", targetNamespace = "http://tempuri.org/")
        String usuarioIntegrador,
        @WebParam(name = "rfcEmisor", targetNamespace = "http://tempuri.org/")
        String rfcEmisor,
        @WebParam(name = "folioUUID", targetNamespace = "http://tempuri.org/")
        String folioUUID);

}
