package com.ferremundo;

public enum Commands {
	RESET_PRODUCT_INVENTORY,
	PRODUCT_INVENTORY_ADD,
	REQUEST_SHOPMAN,
	SEARCH_PRODUCTS,
	SEARCH_PROVIDERS,
	DB_INIT,
	UPDATE_PRODUCTS,
	CALCULATE_RELATIVE_DISCOUNT,
	ABSOLUTE_DISCOUNT, FIX_DB
}
