var result = {
	invoices : [
			{
				"_id" : {
					"$oid" : "4ff74b2724ac36c2b50922d3"
				},
				"json" : "",
				"reference" : "PUQ",
				"invoiceType" : 0,
				"serial" : 0,
				"client" : {
					"code" : "-1",
					"consummer" : "ADAN CORTEZ JACINTO",
					"consummerType" : 1,
					"address" : "CONTADOR IBARROLA (CANADA DE SAN LORENZO #580)",
					"city" : "MORELIA, MICH.",
					"country" : "",
					"state" : "",
					"email" : "",
					"cp" : "",
					"rfc" : "PARA FACTURAR",
					"tel" : "",
					"payment" : 0
				},
				"items" : [
						{
							"quantity" : 1.0,
							"code" : "D457725",
							"mark" : "",
							"unitPrice" : 45.86,
							"unit" : "PZA",
							"description" : "VALVULA ESFERA 1 PVC HCO. CEM. DICA",
							"stored" : 0.0,
							"collecting" : 0.0,
							"sending" : 0.0,
							"requested" : 0.0,
							"missed" : 0.0,
							"productPriceKind" : 1,
							"calls" : 0
						},
						{
							"quantity" : 3.0,
							"code" : "H70725",
							"mark" : "",
							"unitPrice" : 4.03,
							"unit" : "PZA",
							"description" : "CODO HIDR CEM 90- 25 MM",
							"stored" : 0.0,
							"collecting" : 0.0,
							"sending" : 0.0,
							"requested" : 0.0,
							"missed" : 0.0,
							"productPriceKind" : 1,
							"calls" : 0
						},
						{
							"quantity" : 1.0,
							"code" : "H70123825",
							"mark" : "",
							"unitPrice" : 4.11,
							"unit" : "PZA",
							"description" : "REDUC HIDR CEM BUSH  38- 25 MM",
							"stored" : 0.0,
							"collecting" : 0.0,
							"sending" : 0.0,
							"requested" : 0.0,
							"missed" : 0.0,
							"productPriceKind" : 1,
							"calls" : 0
						},
						{
							"quantity" : 2.0,
							"code" : "H70138",
							"mark" : "",
							"unitPrice" : 4.45,
							"unit" : "PZA",
							"description" : "COPLE HIDR CEM  38 MM",
							"stored" : 0.0,
							"collecting" : 0.0,
							"sending" : 0.0,
							"requested" : 0.0,
							"missed" : 0.0,
							"productPriceKind" : 1,
							"calls" : 0
						},
						{
							"quantity" : 1.0,
							"code" : "H71138",
							"mark" : "",
							"unitPrice" : 9.16,
							"unit" : "PZA",
							"description" : "T HIDR CEM  38 MM",
							"stored" : 0.0,
							"collecting" : 0.0,
							"sending" : 0.0,
							"requested" : 0.0,
							"missed" : 0.0,
							"productPriceKind" : 1,
							"calls" : 0
						},
						{
							"quantity" : 3.0,
							"code" : "H73338",
							"mark" : "",
							"unitPrice" : 109.5,
							"unit" : "PZA",
							"description" : "TUERCA UNION 11/2 PVC HCO CEM CED 40 SPEARS",
							"stored" : 0.0,
							"collecting" : 0.0,
							"sending" : 0.0,
							"requested" : 0.0,
							"missed" : 0.0,
							"productPriceKind" : 1,
							"calls" : 0
						},
						{
							"quantity" : 2.0,
							"code" : "D457738",
							"mark" : "",
							"unitPrice" : 96.82,
							"unit" : "PZA",
							"description" : "VALVULA ESFERA 11/2 PVC HCO. CEM. DICA",
							"stored" : 0.0,
							"collecting" : 0.0,
							"sending" : 0.0,
							"requested" : 0.0,
							"missed" : 0.0,
							"productPriceKind" : 1,
							"calls" : 0
						},
						{
							"quantity" : 3.0,
							"code" : "H70738",
							"mark" : "",
							"unitPrice" : 8.33,
							"unit" : "PZA",
							"description" : "CODO HIDR CEM 90- 38 MM",
							"stored" : 0.0,
							"collecting" : 0.0,
							"sending" : 0.0,
							"requested" : 0.0,
							"missed" : 0.0,
							"productPriceKind" : 1,
							"calls" : 0
						},
						{
							"quantity" : 1.0,
							"code" : "H70638",
							"mark" : "",
							"unitPrice" : 21.76,
							"unit" : "PZA",
							"description" : "CODO HIDR CEM 45- 38 MM",
							"stored" : 0.0,
							"collecting" : 0.0,
							"sending" : 0.0,
							"requested" : 0.0,
							"missed" : 0.0,
							"productPriceKind" : 1,
							"calls" : 0
						},
						{
							"quantity" : 1.0,
							"code" : "H73325",
							"mark" : "",
							"unitPrice" : 48.0,
							"unit" : "PZA",
							"description" : "TUERCA UNION 1 PVC HCO CEM CED 40 SPEARS",
							"stored" : 0.0,
							"collecting" : 0.0,
							"sending" : 0.0,
							"requested" : 0.0,
							"missed" : 0.0,
							"productPriceKind" : 1,
							"calls" : 0
						},
						{
							"quantity" : 1.0,
							"code" : "OP480A",
							"mark" : "",
							"unitPrice" : 111.1,
							"unit" : "PZA",
							"description" : "PEGAMENTO P/PVC OATEY 480 GRS AZUL",
							"stored" : 0.0,
							"collecting" : 0.0,
							"sending" : 0.0,
							"requested" : 0.0,
							"missed" : 0.0,
							"productPriceKind" : 1,
							"calls" : 0
						},
						{
							"quantity" : 1.0,
							"code" : "RMT3826",
							"mark" : "",
							"unitPrice" : 18.84,
							"unit" : "MT",
							"description" : "TUBO HIDR CEM RD-26  38 MM   LISO",
							"stored" : 0.0,
							"collecting" : 0.0,
							"sending" : 0.0,
							"requested" : 0.0,
							"missed" : 0.0,
							"productPriceKind" : 1,
							"calls" : 0
						}, {
							"quantity" : 1.0,
							"code" : "RMT2526",
							"mark" : "",
							"unitPrice" : 10.57,
							"unit" : "MT",
							"description" : "TUBO HIDR CEM RD-26  25 MM  LISO",
							"stored" : 0.0,
							"collecting" : 0.0,
							"sending" : 0.0,
							"requested" : 0.0,
							"missed" : 0.0,
							"productPriceKind" : 1,
							"calls" : 0
						} ],
				"metaData" : {
					"invoiceType" : 0,
					"date" : "1310599954000",
					"reference" : "PUQ",
					"serial" : 0
				}
			},
			{
				"_id" : {
					"$oid" : "4ff74b4d24ac36c2b50927cd"
				},
				"json" : "",
				"reference" : "V6V",
				"invoiceType" : 0,
				"serial" : 0,
				"client" : {
					"code" : "-1",
					"consummer" : "ADAN CORTES JACINTO",
					"consummerType" : 1,
					"address" : "",
					"city" : "MORELIA, MICH.",
					"country" : "",
					"state" : "",
					"email" : "",
					"cp" : "",
					"rfc" : "PARA FACTURAR",
					"tel" : "",
					"payment" : 0
				},
				"items" : [ {
					"quantity" : 2.5,
					"code" : "FT19",
					"mark" : "",
					"unitPrice" : 86.23,
					"unit" : "TRAMO",
					"description" : "TUBO 3/4 FUSION CLASE 16 25MM",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 1.0,
					"code" : "F71119",
					"mark" : "",
					"unitPrice" : 6.98,
					"unit" : "PZA",
					"description" : "TEE 3/4 FUSION 25MM",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 3.0,
					"code" : "F70719",
					"mark" : "",
					"unitPrice" : 3.81,
					"unit" : "PZA",
					"description" : "CODO 3/4X90° FUSION 25MM",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 1.0,
					"code" : "F70121913",
					"mark" : "",
					"unitPrice" : 3.18,
					"unit" : "PZA",
					"description" : "REDUCCION 3/4X1/2 FUSION  25-20",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 2.0,
					"code" : "F70119",
					"mark" : "",
					"unitPrice" : 5.08,
					"unit" : "PZA",
					"description" : "COPLE 3/4 FUSION  25MM",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				} ],
				"metaData" : {
					"invoiceType" : 0,
					"date" : "1321649347000",
					"reference" : "V6V",
					"serial" : 0
				}
			},
			{
				"_id" : {
					"$oid" : "4ff74b5724ac36c2b5092912"
				},
				"json" : "",
				"reference" : "YNQ",
				"invoiceType" : 0,
				"serial" : 0,
				"client" : {
					"code" : "-1",
					"consummer" : "NOE CORTEZ JACINTO",
					"consummerType" : 1,
					"address" : "LIC OCTAVIANO",
					"city" : "MORELIA, MICH.",
					"country" : "",
					"state" : "",
					"email" : "",
					"cp" : "",
					"rfc" : "PARA FACTURAR",
					"tel" : "",
					"payment" : 0
				},
				"items" : [ {
					"quantity" : 3.0,
					"code" : "FT19",
					"mark" : "",
					"unitPrice" : 94.85,
					"unit" : "TRAMO",
					"description" : "TUBO 3/4 FUSION CLASE 16 25MM",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 3.0,
					"code" : "FT13",
					"mark" : "",
					"unitPrice" : 51.61,
					"unit" : "TRAMO",
					"description" : "TUBO 1/2 FUSION CLASE 16 20MM",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 1.0,
					"code" : "FT25",
					"mark" : "",
					"unitPrice" : 165.29,
					"unit" : "TRAMO",
					"description" : "TUBO 1 FUSION CLASE 16 32MM",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 2.0,
					"code" : "F70425",
					"mark" : "",
					"unitPrice" : 94.15,
					"unit" : "PZA",
					"description" : "CONECTOR EXTERIOR 1 FUSION 32MM",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 2.0,
					"code" : "F70325",
					"mark" : "",
					"unitPrice" : 84.38,
					"unit" : "PZA",
					"description" : "CONECTOR INTERIOR 1 FUSION 32MM",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 2.0,
					"code" : "F70419",
					"mark" : "",
					"unitPrice" : 32.79,
					"unit" : "PZA",
					"description" : "CONECTOR EXTERIOR 3/4 FUSION 25MM",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 2.0,
					"code" : "F70319",
					"mark" : "",
					"unitPrice" : 28.6,
					"unit" : "PZA",
					"description" : "CONECTOR INTERIOR 3/4 FUSION 25MM",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 2.0,
					"code" : "F70313",
					"mark" : "",
					"unitPrice" : 20.94,
					"unit" : "PZA",
					"description" : "CONECTOR INTERIOR 1/2 FUSION 20MM",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 7.0,
					"code" : "F70719",
					"mark" : "",
					"unitPrice" : 4.19,
					"unit" : "PZA",
					"description" : "CODO 3/4X90° FUSION 25MM",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 2.0,
					"code" : "F71125",
					"mark" : "",
					"unitPrice" : 14.65,
					"unit" : "PZA",
					"description" : "TEE 1 FUSION 32MM",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 3.0,
					"code" : "F70725",
					"mark" : "",
					"unitPrice" : 11.15,
					"unit" : "PZA",
					"description" : "CODO 1X90° FUSION 32MM",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 2.0,
					"code" : "F71119",
					"mark" : "",
					"unitPrice" : 7.68,
					"unit" : "PZA",
					"description" : "TEE 3/4 FUSION 25MM",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 1.0,
					"code" : "F70122513",
					"mark" : "",
					"unitPrice" : 7.68,
					"unit" : "PZA",
					"description" : "REDUCCION 1X1/2 FUSION  32-20",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 3.0,
					"code" : "F70122519",
					"mark" : "",
					"unitPrice" : 8.45,
					"unit" : "PZA",
					"description" : "REDUCCION 1X3/4 FUSION 32-25",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 1.0,
					"code" : "S955",
					"mark" : "",
					"unitPrice" : 390.0,
					"unit" : "PZA",
					"description" : "ROLLO SOLDADURA 95-5 OMEGA SN-PB",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 1.0,
					"code" : "S5050",
					"mark" : "",
					"unitPrice" : 194.35,
					"unit" : "PZA",
					"description" : "ROLLO SOLDADURA 50-50 OMEGA SN-PB",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 1.0,
					"code" : "ML",
					"mark" : "",
					"unitPrice" : 7.07,
					"unit" : "MT",
					"description" : "LIJA ESMERIL P/PLOMERO  ",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 1.0,
					"code" : "SPS250",
					"mark" : "",
					"unitPrice" : 40.64,
					"unit" : "PZA",
					"description" : "PASTA P/SOLDAR 250GRS SILER",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 2.0,
					"code" : "N70325",
					"mark" : "",
					"unitPrice" : 54.47,
					"unit" : "PZA",
					"description" : "CONECTOR ROSCA INTERIOR 1 CO-HI",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 2.0,
					"code" : "N70319",
					"mark" : "",
					"unitPrice" : 23.86,
					"unit" : "PZA",
					"description" : "CONECTOR ROSCA INTERIOR 3/4 CO-HI",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 2.0,
					"code" : "N70419",
					"mark" : "",
					"unitPrice" : 21.22,
					"unit" : "PZA",
					"description" : "CONECTOR ROSCA EXTERIOR 3/4 CO-HI",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				} ],
				"metaData" : {
					"invoiceType" : 0,
					"date" : "1329144386000",
					"reference" : "YNQ",
					"serial" : 0
				}
			},
			{
				"_id" : {
					"$oid" : "4ff74b6424ac36c2b5092ac8"
				},
				"json" : "",
				"reference" : "S1Z",
				"invoiceType" : 0,
				"serial" : 0,
				"client" : {
					"code" : "-1",
					"consummer" : "CRISTINA CORTES JACINTO",
					"consummerType" : 1,
					"address" : "",
					"city" : "MORELIA, MICH.",
					"country" : "",
					"state" : "",
					"email" : "",
					"cp" : "",
					"rfc" : "PARA FACTURAR",
					"tel" : "",
					"payment" : 0
				},
				"items" : [
						{
							"quantity" : 1.0,
							"code" : "ECF01",
							"mark" : "",
							"unitPrice" : 33.12,
							"unit" : "PZA",
							"description" : "TRAMPA NORMAL PVC FLEX",
							"stored" : 0.0,
							"collecting" : 0.0,
							"sending" : 0.0,
							"requested" : 0.0,
							"missed" : 0.0,
							"productPriceKind" : 1,
							"calls" : 0
						},
						{
							"quantity" : 1.0,
							"code" : "CL",
							"mark" : "",
							"unitPrice" : 29.16,
							"unit" : "PZA",
							"description" : "MANGUERA COFLEX VINIL TCA PL CONST LAV-FREG 40CMS",
							"stored" : 0.0,
							"collecting" : 0.0,
							"sending" : 0.0,
							"requested" : 0.0,
							"missed" : 0.0,
							"productPriceKind" : 1,
							"calls" : 0
						}, {
							"quantity" : 2.0,
							"code" : "NPIG",
							"mark" : "",
							"unitPrice" : 39.0,
							"unit" : "PZA",
							"description" : "PIGTAIL TUERCA INVERTIDA NACOBRE",
							"stored" : 0.0,
							"collecting" : 0.0,
							"sending" : 0.0,
							"requested" : 0.0,
							"missed" : 0.0,
							"productPriceKind" : 1,
							"calls" : 0
						}, {
							"quantity" : 1.0,
							"code" : "ST300",
							"mark" : "",
							"unitPrice" : 39.0,
							"unit" : "PZA",
							"description" : "FERRESILICON PENNSYLVANIA 300ML",
							"stored" : 0.0,
							"collecting" : 0.0,
							"sending" : 0.0,
							"requested" : 0.0,
							"missed" : 0.0,
							"productPriceKind" : 1,
							"calls" : 0
						} ],
				"metaData" : {
					"invoiceType" : 0,
					"date" : "1314911679000",
					"reference" : "S1Z",
					"serial" : 0
				}
			},
			{
				"_id" : {
					"$oid" : "4ff74b7c24ac36c2b5092e1d"
				},
				"json" : "",
				"reference" : "YP2",
				"invoiceType" : 0,
				"serial" : 0,
				"client" : {
					"code" : "-1",
					"consummer" : "NOE CORTEZ JACINTO",
					"consummerType" : 1,
					"address" : "STA MARIA",
					"city" : "MORELIA, MICH.",
					"country" : "",
					"state" : "",
					"email" : "",
					"cp" : "",
					"rfc" : "PARA FACTURAR",
					"tel" : "",
					"payment" : 0
				},
				"items" : [ {
					"quantity" : 2.0,
					"code" : "U401SC",
					"mark" : "",
					"unitPrice" : 42.2,
					"unit" : "PZA",
					"description" : "VALVULA ANGULAR COMPACTA  401SC",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				} ],
				"metaData" : {
					"invoiceType" : 0,
					"date" : "1329170843000",
					"reference" : "YP2",
					"serial" : 0
				}
			},
			{
				"_id" : {
					"$oid" : "4ff74b8424ac36c2b5092f35"
				},
				"json" : "",
				"reference" : "XSK",
				"invoiceType" : 0,
				"serial" : 0,
				"client" : {
					"code" : "-1",
					"consummer" : "JACINTO HUMBERTO IRETA ALAS",
					"consummerType" : 1,
					"address" : "JUAN DE DIOS PEZA #283-A COL. LOMAS DE SANTA MARIA",
					"city" : "MORELIA, MICH.",
					"country" : "",
					"state" : "",
					"email" : "",
					"cp" : "58090",
					"rfc" : "IEAJ-420823-8G0",
					"tel" : "",
					"payment" : 0
				},
				"items" : [ {
					"quantity" : 1.0,
					"code" : "NMTCM19",
					"mark" : "",
					"unitPrice" : 97.45,
					"unit" : "MT.",
					"description" : "TUBO 3/4 TIPO M AGUA CO",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 1.0,
					"code" : "N70319",
					"mark" : "",
					"unitPrice" : 23.86,
					"unit" : "PZA",
					"description" : "CONECTOR ROSCA INTERIOR 3/4 CO-HI",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 1.0,
					"code" : "N70325",
					"mark" : "",
					"unitPrice" : 54.47,
					"unit" : "PZA",
					"description" : "CONECTOR ROSCA INTERIOR 1 CO-HI",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 1.0,
					"code" : "N70719",
					"mark" : "",
					"unitPrice" : 13.16,
					"unit" : "PZA",
					"description" : "CODO 3/4X90° CO-CO",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 1.0,
					"code" : "N70119",
					"mark" : "",
					"unitPrice" : 9.2,
					"unit" : "PZA",
					"description" : "COPLE 3/4 CO-CO CON TOPE",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 1.0,
					"code" : "GAS",
					"mark" : "",
					"unitPrice" : 32.0,
					"unit" : "PZA",
					"description" : "CARTUCHO GAS LINMEX 275GRS",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 1.0,
					"code" : "N70125",
					"mark" : "",
					"unitPrice" : 17.17,
					"unit" : "PZA",
					"description" : "COPLE 1 CO-CO CON TOPE",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 1.0,
					"code" : "N70119",
					"mark" : "",
					"unitPrice" : 9.2,
					"unit" : "PZA",
					"description" : "COPLE 3/4 CO-CO CON TOPE",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				} ],
				"metaData" : {
					"invoiceType" : 0,
					"date" : "1327093737000",
					"reference" : "XSK",
					"serial" : 0
				}
			},
			{
				"_id" : {
					"$oid" : "4ff753b624acacea77ea6053"
				},
				"json" : "",
				"reference" : "R6P",
				"invoiceType" : 1,
				"serial" : 0,
				"client" : {
					"code" : "-1",
					"consummer" : "NOE CORTEZ JACINTO",
					"consummerType" : 1,
					"address" : "SRA CRISTNA",
					"city" : "MORELIA, MICH.",
					"country" : "",
					"state" : "",
					"email" : "",
					"cp" : "",
					"rfc" : "",
					"tel" : "",
					"payment" : 0
				},
				"items" : [ {
					"quantity" : 1.0,
					"code" : "JTN",
					"mark" : "",
					"unitPrice" : 120.0,
					"unit" : "PZA",
					"description" : "JUEGO TERMOPAR",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 1.0,
					"code" : "IU111",
					"mark" : "",
					"unitPrice" : 6.0,
					"unit" : "PZA",
					"description" : "PORTALAMPARA BAQUELITA IUSA IU111",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				} ],
				"metaData" : {
					"invoiceType" : 1,
					"date" : "1313171632000",
					"reference" : "R6P",
					"serial" : 0
				}
			},
			{
				"_id" : {
					"$oid" : "4ff753bd24acacea77ea60ef"
				},
				"json" : "",
				"reference" : "Y08",
				"invoiceType" : 1,
				"serial" : 0,
				"client" : {
					"code" : "-1",
					"consummer" : "ADAN CORTEZ JACINTO",
					"consummerType" : 1,
					"address" : "CALLE SEPTIMA",
					"city" : "MORELIA, MICH.",
					"country" : "",
					"state" : "",
					"email" : "",
					"cp" : "",
					"rfc" : "PARA FACTURAR",
					"tel" : "",
					"payment" : 0
				},
				"items" : [ {
					"quantity" : 1.0,
					"code" : "VCF",
					"mark" : "",
					"unitPrice" : 1200.0,
					"unit" : "PZA",
					"description" : "CONTROL DE FLUJO VARS F",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 1.0,
					"code" : "G70123825",
					"mark" : "",
					"unitPrice" : 29.14,
					"unit" : "PZA",
					"description" : "REDUCCION BUSHING 11/2X1 GALVANIZADA",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 1.0,
					"code" : "A701R2519",
					"mark" : "",
					"unitPrice" : 16.24,
					"unit" : "PZA",
					"description" : "REDUCCION CAMPANA 1X3/4 PPR PLATA",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				} ],
				"metaData" : {
					"invoiceType" : 1,
					"date" : "1327523763000",
					"reference" : "Y08",
					"serial" : 0
				}
			},
			{
				"_id" : {
					"$oid" : "4ff753bd24acacea77ea60fd"
				},
				"json" : "",
				"reference" : "SXF",
				"invoiceType" : 1,
				"serial" : 0,
				"client" : {
					"code" : "-1",
					"consummer" : "ADAN CORTES JACINTO",
					"consummerType" : 1,
					"address" : "",
					"city" : "MORELIA, MICH.",
					"country" : "",
					"state" : "",
					"email" : "",
					"cp" : "",
					"rfc" : "PARA FACTURAR",
					"tel" : "",
					"payment" : 0
				},
				"items" : [ {
					"quantity" : 1.0,
					"code" : "NMTCM19",
					"mark" : "",
					"unitPrice" : 104.45,
					"unit" : "MT.",
					"description" : "TUBO 3/4 TIPO M AGUA CO",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 3.0,
					"code" : "N70419",
					"mark" : "",
					"unitPrice" : 21.22,
					"unit" : "PZA",
					"description" : "CONECTOR ROSCA EXTERIOR 3/4 CO-HI",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 1.0,
					"code" : "NTCL13",
					"mark" : "",
					"unitPrice" : 588.5,
					"unit" : "TRAMO",
					"description" : "TUBO 1/2 TIPO L GAS CO",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 1.0,
					"code" : "N70425",
					"mark" : "",
					"unitPrice" : 54.18,
					"unit" : "PZA",
					"description" : "CONECTOR ROSCA EXTERIOR 1 CO-HI",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 1.0,
					"code" : "N70122519",
					"mark" : "",
					"unitPrice" : 19.7,
					"unit" : "PZA",
					"description" : "REDUCCION BUSHING 1X3/4 CO-CO",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 10.0,
					"code" : "N70713",
					"mark" : "",
					"unitPrice" : 5.72,
					"unit" : "PZA",
					"description" : "CODO 1/2X90° CO-CO",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 2.0,
					"code" : "N707313",
					"mark" : "",
					"unitPrice" : 29.57,
					"unit" : "PZA",
					"description" : "CODO CON ROSCA INTERIOR 1/2 90° CO-HI",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 2.0,
					"code" : "IVES13",
					"mark" : "",
					"unitPrice" : 67.5,
					"unit" : "PZA",
					"description" : "VALVULA ESFERA 1/2 SOLD. IUSA",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 4.0,
					"code" : "N70113",
					"mark" : "",
					"unitPrice" : 4.15,
					"unit" : "PZA",
					"description" : "COPLE 1/2 CO-CO CON TOPE",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 4.0,
					"code" : "N71713",
					"mark" : "",
					"unitPrice" : 6.07,
					"unit" : "PZA",
					"description" : "TAPON HEMBRA 1/2 CO",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 2.0,
					"code" : "N71113",
					"mark" : "",
					"unitPrice" : 8.53,
					"unit" : "PZA",
					"description" : "TEE 1/2 CO-CO-CO",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 20.0,
					"code" : "AO13",
					"mark" : "",
					"unitPrice" : 1.52,
					"unit" : "PZA",
					"description" : "ABRAZADERA OMEGA 1/2",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 50.0,
					"code" : "PI1238",
					"mark" : "",
					"unitPrice" : 0.81,
					"unit" : "PZA",
					"description" : "PIJA LAMINA 12X38",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 1.0,
					"code" : "R71150",
					"mark" : "",
					"unitPrice" : 4.5,
					"unit" : "PZA",
					"description" : "T SANIT CEM REX 50- 50 ",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 4.0,
					"code" : "R70650",
					"mark" : "",
					"unitPrice" : 2.68,
					"unit" : "PZA",
					"description" : "CODO SANIT CEM REX 45- 50 MM",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 2.0,
					"code" : "AL50",
					"mark" : "",
					"unitPrice" : 10.1,
					"unit" : "PZA",
					"description" : "ADAPTADOR P/LAVADERO 2 PVC",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 2.0,
					"code" : "RMT50",
					"mark" : "",
					"unitPrice" : 14.04,
					"unit" : "MT",
					"description" : "TUBO SANITARIO NORMA REX  50 MM",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 4.0,
					"code" : "R70750",
					"mark" : "",
					"unitPrice" : 3.13,
					"unit" : "PZA",
					"description" : "CODO SANIT CEM REX 90- 50 MM",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 1.0,
					"code" : "CP480A",
					"mark" : "",
					"unitPrice" : 77.99,
					"unit" : "PZA",
					"description" : "PEGAMENTO PARA PVC CONTACT 480 GRS AZUL",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 1.0,
					"code" : "IVES19",
					"mark" : "",
					"unitPrice" : 98.51,
					"unit" : "PZA",
					"description" : "VALVULA ESFERA 3/4 SOLD. IUSA",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 1.0,
					"code" : "N71119",
					"mark" : "",
					"unitPrice" : 24.63,
					"unit" : "PZA",
					"description" : "TEE 3/4 CO-CO-CO",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 4.0,
					"code" : "N70719",
					"mark" : "",
					"unitPrice" : 13.16,
					"unit" : "PZA",
					"description" : "CODO 3/4X90° CO-CO",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				} ],
				"metaData" : {
					"invoiceType" : 1,
					"date" : "1316889067000",
					"reference" : "SXF",
					"serial" : 0
				}
			},
			{
				"_id" : {
					"$oid" : "4ff753be24acacea77ea610b"
				},
				"json" : "",
				"reference" : "QXY",
				"invoiceType" : 1,
				"serial" : 0,
				"client" : {
					"code" : "-1",
					"consummer" : "ADAN CORTES JACINTO",
					"consummerType" : 1,
					"address" : "",
					"city" : "MORELIA, MICH.",
					"country" : "",
					"state" : "",
					"email" : "",
					"cp" : "",
					"rfc" : "PARA FACTURAR",
					"tel" : "",
					"payment" : 0
				},
				"items" : [ {
					"quantity" : 10.0,
					"code" : "N70738",
					"mark" : "",
					"unitPrice" : 107.86,
					"unit" : "PZA",
					"description" : "CODO 11/2X90° CO-CO",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 10.0,
					"code" : "N70138",
					"mark" : "",
					"unitPrice" : 33.64,
					"unit" : "PZA",
					"description" : "COPLE 11/2 CO-CO CON TOPE",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 0.5,
					"code" : "NMTCM32",
					"mark" : "",
					"unitPrice" : 260.13,
					"unit" : "MT.",
					"description" : "TUBO 11/4 TIPO M AGUA CO",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 1.0,
					"code" : "N70123832",
					"mark" : "",
					"unitPrice" : 41.38,
					"unit" : "PZA",
					"description" : "REDUCCION BUSHING 11/2X11/4 CO-CO",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 1.0,
					"code" : "N70432",
					"mark" : "",
					"unitPrice" : 96.12,
					"unit" : "PZA",
					"description" : "CONECTOR ROSCA EXTERIOR 11/4 CO-HI",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				} ],
				"metaData" : {
					"invoiceType" : 1,
					"date" : "1312651238000",
					"reference" : "QXY",
					"serial" : 0
				}
			},
			{
				"_id" : {
					"$oid" : "4ff753c124acacea77ea616c"
				},
				"json" : "",
				"reference" : "T1O",
				"invoiceType" : 1,
				"serial" : 0,
				"client" : {
					"code" : "-1",
					"consummer" : "NOE CORTES JACINTO",
					"consummerType" : 1,
					"address" : "SRA. NARANJO",
					"city" : "MORELIA, MICH.",
					"country" : "",
					"state" : "",
					"email" : "",
					"cp" : "",
					"rfc" : "PARA FACTURAR",
					"tel" : "",
					"payment" : 0
				},
				"items" : [ {
					"quantity" : 2.0,
					"code" : "ST300",
					"mark" : "",
					"unitPrice" : 39.0,
					"unit" : "PZA",
					"description" : "FERRESILICON PENNSYLVANIA 300ML",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 2.0,
					"code" : "RSD",
					"mark" : "",
					"unitPrice" : 260.0,
					"unit" : "PZA",
					"description" : "SISTEMA DUO ROTOPLAS",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 2.0,
					"code" : "CWCV",
					"mark" : "",
					"unitPrice" : 41.06,
					"unit" : "PZA",
					"description" : "MANGUERA COFLEX VINIL WC 35CMS",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				} ],
				"metaData" : {
					"invoiceType" : 1,
					"date" : "1317227949000",
					"reference" : "T1O",
					"serial" : 0
				}
			},
			{
				"_id" : {
					"$oid" : "4ff753c224acacea77ea619c"
				},
				"json" : "",
				"reference" : "ZSL",
				"invoiceType" : 1,
				"serial" : 0,
				"client" : {
					"code" : "-1",
					"consummer" : "ADAN CORTEZ JACINTO",
					"consummerType" : 1,
					"address" : "",
					"city" : "MORELIA, MICH.",
					"country" : "",
					"state" : "",
					"email" : "",
					"cp" : "",
					"rfc" : "PARA FACTURAR",
					"tel" : "",
					"payment" : 0
				},
				"items" : [ {
					"quantity" : 1.0,
					"code" : "L1925",
					"mark" : "",
					"unitPrice" : 402.65,
					"unit" : "PZA",
					"description" : "REGULADOR LOBO B. PRESION 3/4X1",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 1.0,
					"code" : "G70121913",
					"mark" : "",
					"unitPrice" : 7.59,
					"unit" : "PZA",
					"description" : "REDUCCION BUSHING 3/4X1/2 GALVANIZADA",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 1.0,
					"code" : "G7012136",
					"mark" : "",
					"unitPrice" : 7.81,
					"unit" : "PZA",
					"description" : "REDUCCION BUSHING 1/2X1/4 GALVANIZADA",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 1.0,
					"code" : "G70122513",
					"mark" : "",
					"unitPrice" : 18.24,
					"unit" : "PZA",
					"description" : "REDUCCION BUSHING 1X1/2 GALVANIZADA",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				} ],
				"metaData" : {
					"invoiceType" : 1,
					"date" : "1331315968000",
					"reference" : "ZSL",
					"serial" : 0
				}
			},
			{
				"_id" : {
					"$oid" : "4ff753c524acacea77ea61e7"
				},
				"json" : "",
				"reference" : "10O2",
				"invoiceType" : 1,
				"serial" : 0,
				"client" : {
					"code" : "-1",
					"consummer" : "ADAN CORTEZ JACINTO",
					"consummerType" : 1,
					"address" : "BALNEARIO VISTA BELLA",
					"city" : "MORELIA, MICH.",
					"country" : "",
					"state" : "",
					"email" : "",
					"cp" : "",
					"rfc" : "PARA FACTURAR",
					"tel" : "",
					"payment" : 0
				},
				"items" : [ {
					"quantity" : 2.0,
					"code" : "H71175",
					"mark" : "",
					"unitPrice" : 175.53,
					"unit" : "PZA",
					"description" : "T HIDR CEM  75 MM",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 4.0,
					"code" : "H70127550",
					"mark" : "",
					"unitPrice" : 25.63,
					"unit" : "PZA",
					"description" : "REDUC HIDR CEM BUSH  75- 50 MM",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 2.0,
					"code" : "H70125038",
					"mark" : "",
					"unitPrice" : 4.85,
					"unit" : "PZA",
					"description" : "REDUC HIDR CEM BUSH  50- 38 MM",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 2.0,
					"code" : "H70123825",
					"mark" : "",
					"unitPrice" : 4.11,
					"unit" : "PZA",
					"description" : "REDUC HIDR CEM BUSH  38- 25 MM",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 1.0,
					"code" : "OP480V",
					"mark" : "",
					"unitPrice" : 135.63,
					"unit" : "PZA",
					"description" : "PEGAMENTO P/PVC OATEY 480 GRS VERDE",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				} ],
				"metaData" : {
					"invoiceType" : 1,
					"date" : "1333207998000",
					"reference" : "10O2",
					"serial" : 0
				}
			},
			{
				"_id" : {
					"$oid" : "4ff753c624acacea77ea61fc"
				},
				"json" : "",
				"reference" : "R3B",
				"invoiceType" : 1,
				"serial" : 0,
				"client" : {
					"code" : "-1",
					"consummer" : "ADAN CORTES JACINTO",
					"consummerType" : 1,
					"address" : "SRA TREVINO",
					"city" : "MORELIA, MICH.",
					"country" : "",
					"state" : "",
					"email" : "",
					"cp" : "",
					"rfc" : "PARA FACTURAR",
					"tel" : "",
					"payment" : 0
				},
				"items" : [ {
					"quantity" : 2.0,
					"code" : "CB4L",
					"mark" : "",
					"unitPrice" : 115.32,
					"unit" : "PZA",
					"description" : "BRIDA FLEXIBLE LARGA P/TUBERÍA DE 4",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 2.0,
					"code" : "JS",
					"mark" : "",
					"unitPrice" : 10.0,
					"unit" : "PZA",
					"description" : "JUNTA P/WC CERA SENCILLA 2000",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 2.0,
					"code" : "PWC",
					"mark" : "",
					"unitPrice" : 5.05,
					"unit" : "PZA",
					"description" : "JGO. PIJAS P/WC",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 1.0,
					"code" : "ST300",
					"mark" : "",
					"unitPrice" : 39.0,
					"unit" : "PZA",
					"description" : "FERRESILICON PENNSYLVANIA 300ML",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 4.0,
					"code" : "T3/8",
					"mark" : "",
					"unitPrice" : 0.43,
					"unit" : "PZA",
					"description" : "TAQUETE PLASTICO 3/8 ELPRO",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				} ],
				"metaData" : {
					"invoiceType" : 1,
					"date" : "1313006588000",
					"reference" : "R3B",
					"serial" : 0
				}
			},
			{
				"_id" : {
					"$oid" : "4ff753c624acacea77ea620a"
				},
				"json" : "",
				"reference" : "YXD",
				"invoiceType" : 1,
				"serial" : 0,
				"client" : {
					"code" : "-1",
					"consummer" : "NOE CORTEZ JACINTO",
					"consummerType" : 1,
					"address" : "",
					"city" : "MORELIA, MICH.",
					"country" : "",
					"state" : "",
					"email" : "",
					"cp" : "",
					"rfc" : "PARA FACTURAR",
					"tel" : "",
					"payment" : 0
				},
				"items" : [ {
					"quantity" : 2.0,
					"code" : "CB4L",
					"mark" : "",
					"unitPrice" : 115.32,
					"unit" : "PZA",
					"description" : "BRIDA FLEXIBLE LARGA P/TUBERÍA DE 4",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 2.0,
					"code" : "JS",
					"mark" : "",
					"unitPrice" : 10.0,
					"unit" : "PZA",
					"description" : "JUNTA P/WC CERA SENCILLA 2000",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 2.0,
					"code" : "PWC",
					"mark" : "",
					"unitPrice" : 5.05,
					"unit" : "PZA",
					"description" : "JGO. PIJAS P/WC",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 2.0,
					"code" : "ST300",
					"mark" : "",
					"unitPrice" : 39.0,
					"unit" : "PZA",
					"description" : "FERRESILICON PENNSYLVANIA 300ML",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 4.0,
					"code" : "U401SC",
					"mark" : "",
					"unitPrice" : 42.2,
					"unit" : "PZA",
					"description" : "VALVULA ANGULAR COMPACTA  401SC",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 4.0,
					"code" : "CWCV",
					"mark" : "",
					"unitPrice" : 41.06,
					"unit" : "PZA",
					"description" : "MANGUERA COFLEX VINIL WC 35CMS",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 3.0,
					"code" : "MS5050",
					"mark" : "",
					"unitPrice" : 32.39,
					"unit" : "MT",
					"description" : "SOLDADURA OMEGA 50-50 SN-PB",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 1.5,
					"code" : "MS955",
					"mark" : "",
					"unitPrice" : 65.0,
					"unit" : "MT",
					"description" : "SOLDADURA OMEGA 95-5 SN-PB",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				} ],
				"metaData" : {
					"invoiceType" : 1,
					"date" : "1329579537000",
					"reference" : "YXD",
					"serial" : 0
				}
			},
			{
				"_id" : {
					"$oid" : "4ff753c624acacea77ea6216"
				},
				"json" : "",
				"reference" : "TNX",
				"invoiceType" : 1,
				"serial" : 0,
				"client" : {
					"code" : "-1",
					"consummer" : "CP IBARROLA",
					"consummerType" : 1,
					"address" : "ADAN CORTES JACINTO",
					"city" : "MORELIA, MICH.",
					"country" : "",
					"state" : "",
					"email" : "",
					"cp" : "",
					"rfc" : "PARA FACTURAR",
					"tel" : "",
					"payment" : 0
				},
				"items" : [ {
					"quantity" : 1.0,
					"code" : "G70123225",
					"mark" : "",
					"unitPrice" : 24.71,
					"unit" : "PZA",
					"description" : "REDUCCION BUSHING 11/4X1 GALVANIZADA",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				} ],
				"metaData" : {
					"invoiceType" : 1,
					"date" : "1318515321000",
					"reference" : "TNX",
					"serial" : 0
				}
			},
			{
				"_id" : {
					"$oid" : "4ff753d024acacea77ea6362"
				},
				"json" : "",
				"reference" : "PW7",
				"invoiceType" : 1,
				"serial" : 0,
				"client" : {
					"code" : "-1",
					"consummer" : "CRISTINA CORTEZ JACINTO",
					"consummerType" : 1,
					"address" : "FRACC.SANTA MARIA",
					"city" : "MORELIA, MICH.",
					"country" : "",
					"state" : "",
					"email" : "",
					"cp" : "",
					"rfc" : "PARA FACTURAR",
					"tel" : "",
					"payment" : 0
				},
				"items" : [
						{
							"quantity" : 1.0,
							"code" : "ST75",
							"mark" : "",
							"unitPrice" : 20.0,
							"unit" : "PZA",
							"description" : "SILICON PENNSYLVANIA USO GRAL. 75ML",
							"stored" : 0.0,
							"collecting" : 0.0,
							"sending" : 0.0,
							"requested" : 0.0,
							"missed" : 0.0,
							"productPriceKind" : 1,
							"calls" : 0
						},
						{
							"quantity" : 1.0,
							"code" : "CWC",
							"mark" : "",
							"unitPrice" : 31.95,
							"unit" : "PZA",
							"description" : "MANGUERA COFLEX VINIL TCA PL CONST WC 35CMS",
							"stored" : 0.0,
							"collecting" : 0.0,
							"sending" : 0.0,
							"requested" : 0.0,
							"missed" : 0.0,
							"productPriceKind" : 1,
							"calls" : 0
						}, {
							"quantity" : 1.0,
							"code" : "AXN0913",
							"mark" : "",
							"unitPrice" : 208.56,
							"unit" : "PZA",
							"description" : "SITEMA DUO P/WC ALFA 3 Y 6 LTS",
							"stored" : 0.0,
							"collecting" : 0.0,
							"sending" : 0.0,
							"requested" : 0.0,
							"missed" : 0.0,
							"productPriceKind" : 1,
							"calls" : 0
						} ],
				"metaData" : {
					"invoiceType" : 1,
					"date" : "1310675774000",
					"reference" : "PW7",
					"serial" : 0
				}
			},
			{
				"_id" : {
					"$oid" : "4ff753d124acacea77ea6382"
				},
				"json" : "",
				"reference" : "QOO",
				"invoiceType" : 1,
				"serial" : 0,
				"client" : {
					"code" : "-1",
					"consummer" : "CRISTINA CORTES JACINTO",
					"consummerType" : 1,
					"address" : "BAR DEL CENTRO",
					"city" : "MORELIA, MICH.",
					"country" : "",
					"state" : "",
					"email" : "",
					"cp" : "",
					"rfc" : "PARA FACTURAR",
					"tel" : "",
					"payment" : 0
				},
				"items" : [
						{
							"quantity" : 1.0,
							"code" : "R7000",
							"mark" : "",
							"unitPrice" : 70.7,
							"unit" : "PZA",
							"description" : "REGULADOR P/GAS 7000 A. P. ROSTICERO",
							"stored" : 0.0,
							"collecting" : 0.0,
							"sending" : 0.0,
							"requested" : 0.0,
							"missed" : 0.0,
							"productPriceKind" : 1,
							"calls" : 0
						},
						{
							"quantity" : 1.0,
							"code" : "PPRC",
							"mark" : "",
							"unitPrice" : 14.12,
							"unit" : "PZA",
							"description" : "PUNTA POOL CON ROSCA CHICA",
							"stored" : 0.0,
							"collecting" : 0.0,
							"sending" : 0.0,
							"requested" : 0.0,
							"missed" : 0.0,
							"productPriceKind" : 1,
							"calls" : 0
						},
						{
							"quantity" : 1.0,
							"code" : "TI",
							"mark" : "",
							"unitPrice" : 10.39,
							"unit" : "PZA",
							"description" : "TUERCA IZQUIERDA P/PIGTAIL NACOBRE",
							"stored" : 0.0,
							"collecting" : 0.0,
							"sending" : 0.0,
							"requested" : 0.0,
							"missed" : 0.0,
							"productPriceKind" : 1,
							"calls" : 0
						},
						{
							"quantity" : 2.0,
							"code" : "CE1013",
							"mark" : "",
							"unitPrice" : 34.39,
							"unit" : "PZA",
							"description" : "CODO ESTUFA 3/8X1/2 P/GAS",
							"stored" : 0.0,
							"collecting" : 0.0,
							"sending" : 0.0,
							"requested" : 0.0,
							"missed" : 0.0,
							"productPriceKind" : 1,
							"calls" : 0
						},
						{
							"quantity" : 1.0,
							"code" : "NT106",
							"mark" : "",
							"unitPrice" : 10.23,
							"unit" : "PZA",
							"description" : "NIPLE TERMINAL 3/8X1/4 P/GAS",
							"stored" : 0.0,
							"collecting" : 0.0,
							"sending" : 0.0,
							"requested" : 0.0,
							"missed" : 0.0,
							"productPriceKind" : 1,
							"calls" : 0
						},
						{
							"quantity" : 1.0,
							"code" : "CG100",
							"mark" : "",
							"unitPrice" : 62.87,
							"unit" : "PZA",
							"description" : "MANGUERA COFLEX VINIL 3/8X3/8 P/GAS 100CMS",
							"stored" : 0.0,
							"collecting" : 0.0,
							"sending" : 0.0,
							"requested" : 0.0,
							"missed" : 0.0,
							"productPriceKind" : 1,
							"calls" : 0
						},
						{
							"quantity" : 2.0,
							"code" : "CG60",
							"mark" : "",
							"unitPrice" : 51.67,
							"unit" : "PZA",
							"description" : "MANGUERA COFLEX VINIL 3/8X3/8 P/GAS 60CMS",
							"stored" : 0.0,
							"collecting" : 0.0,
							"sending" : 0.0,
							"requested" : 0.0,
							"missed" : 0.0,
							"productPriceKind" : 1,
							"calls" : 0
						}, {
							"quantity" : 1.0,
							"code" : "CTF1/2",
							"mark" : "",
							"unitPrice" : 3.1,
							"unit" : "PZA",
							"description" : "CINTA DE TEFLON 1/2",
							"stored" : 0.0,
							"collecting" : 0.0,
							"sending" : 0.0,
							"requested" : 0.0,
							"missed" : 0.0,
							"productPriceKind" : 1,
							"calls" : 0
						} ],
				"metaData" : {
					"invoiceType" : 1,
					"date" : "1312295594000",
					"reference" : "QOO",
					"serial" : 0
				}
			}, {
				"_id" : {
					"$oid" : "4ff753d524acacea77ea6406"
				},
				"json" : "",
				"reference" : "YXE",
				"invoiceType" : 1,
				"serial" : 0,
				"client" : {
					"code" : "-1",
					"consummer" : "NOE CORTEZ JACINTO",
					"consummerType" : 1,
					"address" : "SRA YETZA",
					"city" : "MORELIA, MICH.",
					"country" : "",
					"state" : "",
					"email" : "",
					"cp" : "",
					"rfc" : "PARA FACTURAR",
					"tel" : "",
					"payment" : 0
				},
				"items" : [ {
					"quantity" : 1.0,
					"code" : "CVA",
					"mark" : "",
					"unitPrice" : 180.97,
					"unit" : "PZA",
					"description" : "VALVULA DE ALIVIO P/BOILER 3/4 ",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 1.0,
					"code" : "MG07",
					"mark" : "",
					"unitPrice" : 363.6,
					"unit" : "PZA",
					"description" : "MANOMETRO GLICERINA ALTAMIRA 0-7KGS",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				} ],
				"metaData" : {
					"invoiceType" : 1,
					"date" : "1329579573000",
					"reference" : "YXE",
					"serial" : 0
				}
			}, {
				"_id" : {
					"$oid" : "4ff753d524acacea77ea6409"
				},
				"json" : "",
				"reference" : "V9H",
				"invoiceType" : 1,
				"serial" : 0,
				"client" : {
					"code" : "-1",
					"consummer" : "ADAN CORTES JACINTO",
					"consummerType" : 1,
					"address" : "",
					"city" : "MORELIA, MICH.",
					"country" : "",
					"state" : "",
					"email" : "",
					"cp" : "",
					"rfc" : "PARA FACTURAR",
					"tel" : "",
					"payment" : 0
				},
				"items" : [ {
					"quantity" : 1.0,
					"code" : "EFE",
					"mark" : "",
					"unitPrice" : 275.73,
					"unit" : "PZA",
					"description" : "FLOTADOR SUMERGIBLE EVANS 2MTS",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 1.0,
					"code" : "U04N13",
					"mark" : "",
					"unitPrice" : 93.49,
					"unit" : "PZA",
					"description" : "VALVULA FLOTADOR 1/2 FIG. 04N",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				}, {
					"quantity" : 1.0,
					"code" : "FC6",
					"mark" : "",
					"unitPrice" : 90.54,
					"unit" : "PZA",
					"description" : "FLOTADOR COBRE P/TINACO #6",
					"stored" : 0.0,
					"collecting" : 0.0,
					"sending" : 0.0,
					"requested" : 0.0,
					"missed" : 0.0,
					"productPriceKind" : 1,
					"calls" : 0
				} ],
				"metaData" : {
					"invoiceType" : 1,
					"date" : "1321981138000",
					"reference" : "V9H",
					"serial" : 0
				}
			} ]
}